### ISSUE TITLE
Java outputs are zero

### ISSUE THREAD

**Issue by abhinav-adtechs** [blakeMilner/real_time_QRS_detection#1]
The java code with the given data and (also with real ecg data) is not providing any output. 
Also, please go through the Pan Tompkin's paper for the actual number of filtering techniques used. Some methods seem to be missing.

**Comment by blakeMilner** [comment]
Hi,

This is an abridged version of the technique used in the original paper. It
works just as well.

**Comment by abhinav-adtechs** [comment]
I built the code without a single modification. The output csv file has 0s filled.

**Comment by rickin7** [comment]
I loaded the files on net beans but there is no output obtained, although the project builds correctly

**Comment by abhinav-adtechs** [comment]
_In reference to Java:_ 
Did you try with real ECG readings? 
An output csv file will be generated with 1s representing the peaks. Check code to know the exact path of the csv file.
However, all the steps of Pan Tompkins algorithm are not implemented in this.
